heat_template_version: 2013-05-23

description: 
        Create a SLURM cluster based on the parameters in params.yaml

parameters:

  key-name:
    type: string
    description: SSH key
    default: centos-vanloo-admin

  net-id:
    type: string
    description: Network ID

  subnet-id:
    type: string
    description: Subnet ID

  head-image:
    type: string
    default: centos-7.1-1509-x86_64
    description: Glance image for head instance

  compute-image:
    type: string
    default: centos-7.1-1509-x86_64
    description: Glance image for compute instance

  host-prefix:
    type: string
    default: compute
    description: Compute node hostname prefix

  head-flavor:
    type: string
    default: m1.large
    description: Head instance flavour

  compute-flavor:
    type: string
    default: m1.medium
    description: Compute instance flavour

  nameserver:
    type: string
    description: DNS server for the cluster
    default: 8.8.8.8

  compute-count:
    type: string
    description: Number of compute node instances
    default: 10

  timeout:
    type: number
    description: Timeout for WaitCondition
    default: 1200


resources:
  instance1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: 'key-name' }
      image: { get_param: 'head-image' }
      flavor: { get_param: 'head-flavor' }
      name:
        str_replace:
          template: "base%-head"
          params:
            base%: { get_param: 'OS::stack_name' }
      networks:
        - port: { get_resource: 'instance1-port' }
      user_data_format: RAW

  instance1-port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: 'net-id' }
      fixed_ips:
        - subnet_id: { get_param: 'subnet-id' }

