heat_template_version: 2013-05-23

description: 
        Create a SLURM cluster based on the parameters in params.yaml

parameters:

  key-name:
    type: string
    description: SSH key
    default: centos-vanloo-admin

  net-id:
    type: string
    description: Network ID

  subnet-id:
    type: string
    description: Subnet ID

  head-image:
    type: string
    default: centos-7.1-1509-x86_64
    description: Glance image for head instance

  compute-image:
    type: string
    default: centos-7.1-1509-x86_64
    description: Glance image for compute instance

  host-prefix:
    type: string
    default: compute
    description: Compute node hostname prefix

  head-flavor:
    type: string
    default: m1.large
    description: Head instance flavour

  compute-flavor:
    type: string
    default: m1.medium
    description: Compute instance flavour

  nameserver:
    type: string
    description: DNS server for the cluster
    default: 8.8.8.8

  compute-count:
    type: string
    description: Number of compute node instances
    default: 10

  timeout:
    type: number
    description: Timeout for WaitCondition
    default: 1200


resources:
  head-wait-handle:
    type: "AWS::CloudFormation::WaitConditionHandle"

  head-wait-condition:
    type: "AWS::CloudFormation::WaitCondition"
    depends_on:
      - head
    properties:
      Handle:
        get_resource: head-wait-handle
      Timeout: "2400"

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: local-root
      save_private_key: true

  ssh-icmp:
    type: OS::Neutron::SecurityGroup
    properties:
      name: ssh-icmp
      description: SSH and Ping
      rules:
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - protocol: icmp

  nfs-server:
    type: OS::Neutron::SecurityGroup
    properties:
      name: nfs-server
      description: NFS
      rules:
      - protocol: tcp
        port_range_min: 111
        port_range_max: 111
      - protocol: tcp
        port_range_min: 1110
        port_range_max: 1110
      - protocol: tcp
        port_range_min: 2049
        port_range_max: 2049
      - protocol: tcp
        port_range_min: 4045
        port_range_max: 4045
      - protocol: udp
        port_range_min: 111
        port_range_max: 111
      - protocol: udp
        port_range_min: 1110
        port_range_max: 1110       
      - protocol: udp
        port_range_min: 2049
        port_range_max: 2049
      - protocol: udp
        port_range_min: 4045
        port_range_max: 4045


 head:
   type: OS::Nova::Server
    properties:
      key_name: { get_param: 'key-name' }
      image: { get_param: 'head-image' }
      flavor: { get_param: 'head-flavor' }
      name:
        str_replace:
          template: "base%-head"
          params:
            base%: { get_param: 'OS::stack_name' }
      networks:
        - port: { get_resource: 'head-port' }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            #
            curl https://copr.fedoraproject.org/coprs/verdurin/slurm/repo/epel-7/verdurin-slurm-epel-7.repo  -o /etc/yum.repos.d/verdurin-slurm-epel-7.repo

            yum -y install slurm slurm-munge slurm-slurmdbd slurm-plugins

            curl -T /tmp/wait-data '$WAIT-HANDLE'
      params:
        "$WAIT-HANDLE":
          get_resource: head-wait-handle
      security_groups:
        - { get_resource: 'ssh-icmp' }
        - { get_resource: 'nfs-server' }
        - { get_resource: 'slurm' }

  head-port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: 'net-id' }
      fixed_ips:
        - subnet_id: { get_param: 'subnet-id' }

 compute-group:
   type: OS::Heat::ResourceGroup
   depends on: head-wait-condition
